import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import Footer from "@/components/footer";

const inter = Inter({
    variable: "--font-inter",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.variable} antialiased bg-[#f4f4f4]`}>
                <Nav />
                <section className="min-h-[50dvh] py-10 px-6">
                    <div className="max-w-7xl mx-auto">{children}</div>
                </section>
                <Footer />
            </body>
        </html>
    );
}
